---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:

  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: lab-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8000
              name: metrics
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: RMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: host
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: username
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
    # Label for ServiceMonitor selector
    prometheus-scrape: "true"
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
