apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app
  labels:
    app: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: lab-worker:v1
          imagePullPolicy: Never
          env:
            - name: RMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: host
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: username
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
